### PR TITLE
[ENTVTX-146] add a workaround for CLOUD-2195

### PR DESCRIPTION
**Pull request by Ladicek**

### CODE REVIEW

**Comment by cescoffier** [comment]
Shouldn't the `.openshiftio/service.yaml` file also be updated?

**Comment by Ladicek** [comment]
Woooo +10000, thanks!!!

**Comment by Ladicek** [comment]
Thanks again, fixed in both Vert.x and Spring Boot pull requests; for some reason, the WildFly Swarm SSO booster doesn't have anything in the `.openshiftio` directory...

**Comment by cescoffier** [comment]
Thanks!

**Pull request merged**
